Bootstrap: docker
From: debian:latest

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-kakoune
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2022.10.31

%post
    apt update
    apt upgrade -y
    apt install -y kakoune
